# -*- coding: utf-8 -*-
"""Generate remaining Isaiah chapters 46-48."""
import json

def w(ch, preamble, verses):
    data = {"meta": {"project": "The Covenant Rendering", "version": "1.0.0", "book": "Isaiah", "chapter": ch, "source_text": "Westminster Leningrad Codex (WLC)", "reference_text": "KJV", "generated_at": "2026-03-31T00:00:00Z", "prompt_version": "1.3", "license": "CC-BY-4.0"}, "preamble": preamble, "verses": verses}
    with open(f'isaiah/chapter-{ch:02d}.json', 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  ch{ch}: {len(verses)}v")

# ISAIAH 46
w(46, {
    "summary": "Bel and Nebo, Babylon's chief gods, are loaded onto weary animals as dead weight. In contrast, God has carried Israel from the womb and will carry them to old age. The idol-maker fashions a god that cannot move; the LORD announces the end from the beginning and calls a bird of prey from the east.",
    "remarkable": "The chapter's theological argument is built on a single contrast: who carries whom? Babylonian gods must be carried by their worshippers (vv. 1-2); Israel's God carries His worshippers (vv. 3-4). The four first-person verbs of verse 4 — 'I have made, I will bear, I will carry, I will deliver' — trace God's commitment from creation through sustenance to salvation. The declaration 'I am God, and there is no other' (v. 9) combined with 'I declare the end from the beginning' (v. 10) identifies foreknowledge as the proof of divinity no idol can match.",
    "friction": "Bel (equivalent to Marduk, Babylon's chief deity) and Nebo (Nabu, god of writing, whose name appears in Nebuchadnezzar) are introduced being packed onto animals as their city falls. We transliterated both and noted their significance. The 'bird of prey from the east' (v. 11) is Cyrus — the metaphor emphasizes speed and inevitability.",
    "connections": "The carried-vs-carrying contrast anticipates the Dagon episode (1 Samuel 5:1-4). The 'from the womb to old age' promise echoes Psalm 71:5-6, 17-18. Cyrus as the bird of prey connects to 41:2 and 44:28-45:1. The idol-making satire continues from 40:18-20 and 44:9-20."
}, [
    {"verse": 1, "text_hebrew": "\u05db\u05bc\u05b8\u05e8\u05b7\u05e2 \u05d1\u05bc\u05b5\u05dc \u05e7\u05b9\u05e8\u05b5\u05e1 \u05e0\u05b0\u05d1\u05d5\u05b9", "text_kjv": "Bel boweth down, Nebo stoopeth, their idols were upon the beasts, and upon the cattle: your carriages were heavy loaden; they are a burden to the weary beast.", "rendering": "Bel bows down, Nebo stoops low.\nTheir images are loaded on beasts and cattle.\nThe things you carry are burdens,\na load for weary animals.", "translator_notes": ["Bel is the Babylonian supreme deity (equivalent to Marduk); Nebo (Nabu) is the god of writing, whose name appears in Nebuchadnezzar ('Nebo, protect the boundary'). The scene is Babylon's fall: its gods are packed onto donkeys for transport. The verbs kara ('bows') and qores ('stoops') describe collapse, not worship."], "key_terms": [{"hebrew": "\u05d1\u05bc\u05b5\u05dc / \u05e0\u05b0\u05d1\u05d5\u05b9", "transliteration": "Bel / Nebo", "rendered_as": "Bel / Nebo", "semantic_range": "Babylonian deities: Bel (Marduk, chief god), Nebo (Nabu, god of wisdom and writing)", "note": "These are the two most important Babylonian deities, now portrayed as dead weight on pack animals."}], "reading_level": "9th grade"},
    {"verse": 2, "text_hebrew": "\u05e7\u05b8\u05e8\u05b0\u05e1\u05d5\u05bc \u05db\u05b8\u05e8\u05b0\u05e2\u05d5\u05bc \u05d9\u05b7\u05d7\u05b0\u05d3\u05bc\u05b8\u05d5", "text_kjv": "They stoop, they bow down together; they could not deliver the burden, but themselves are gone into captivity.", "rendering": "They stoop, they bow down together;\nthey cannot rescue the burden,\nand they themselves go into captivity.", "translator_notes": ["The gods go into captivity (shevi) alongside their people. A god that can be exiled is no god at all."], "reading_level": "9th grade"},
    {"verse": 3, "text_hebrew": "\u05e9\u05c1\u05b4\u05de\u05b0\u05e2\u05d5\u05bc \u05d0\u05b5\u05dc\u05b7\u05d9 \u05d1\u05bc\u05b5\u05d9\u05ea \u05d9\u05b7\u05e2\u05b2\u05e7\u05b9\u05d1", "text_kjv": "Hearken unto me, O house of Jacob, and all the remnant of the house of Israel, which are borne by me from the belly, which are carried from the womb:", "rendering": "Listen to me, house of Jacob,\nall the remnant of the house of Israel,\nyou who have been carried from the womb,\nborne from birth:", "translator_notes": ["The contrast is immediate: Babylonian gods are carried by their people; Israel is carried by their God. The same verbs for 'carried' and 'borne' apply to both — but the direction reverses."], "reading_level": "9th grade"},
    {"verse": 4, "text_hebrew": "\u05d5\u05b0\u05e2\u05b7\u05d3\u05be\u05d6\u05b4\u05e7\u05b0\u05e0\u05b8\u05d4 \u05d0\u05b2\u05e0\u05b4\u05d9 \u05d4\u05d5\u05bc\u05d0", "text_kjv": "And even to your old age I am he; and even to hoar hairs will I carry you: I have made, and I will bear; even I will carry, and will deliver you.", "rendering": "Even to your old age I am He,\nand to grey hairs I will carry you.\nI have made, and I will bear;\nI will carry, and I will deliver.", "expanded_rendering": "Four first-person verbs in rapid succession express God's total commitment: asiti ('I have made'), essa ('I will bear'), esbol ('I will carry'), amallet ('I will deliver'). God created Israel and will sustain them through every stage of life. The contrast with Bel and Nebo is absolute: they must be carried; God carries.", "translator_notes": ["The emphatic ani hu ('I am He') is God's self-identification formula throughout Second Isaiah. The four verbs trace a complete arc: creation, sustenance, bearing, deliverance."], "reading_level": "9th grade"},
    {"verse": 5, "text_hebrew": "\u05dc\u05b0\u05de\u05b4\u05d9 \u05ea\u05b0\u05d3\u05b7\u05de\u05bc\u05b0\u05d9\u05d5\u05bc\u05e0\u05b4\u05d9", "text_kjv": "To whom will ye liken me, and make me equal, and compare me, that we may be like?", "rendering": "To whom will you liken me\nor make me equal?\nTo whom will you compare me,\nas though we were alike?", "translator_notes": ["The incomparability challenge echoes 40:18, 25 — three verbs eliminate every basis for comparison."], "reading_level": "9th grade"},
    {"verse": 6, "text_hebrew": "\u05d4\u05b7\u05d6\u05bc\u05b8\u05dc\u05b4\u05d9\u05dd \u05d6\u05b8\u05d4\u05b8\u05d1 \u05de\u05b4\u05db\u05bc\u05b4\u05d9\u05e1", "text_kjv": "They lavish gold out of the bag, and weigh silver in the balance, and hire a goldsmith; and he maketh it a god: they fall down, yea, they worship.", "rendering": "Those who lavish gold from their purses\nand weigh out silver on the scales\nhire a goldsmith, and he makes it into a god.\nThey bow down \u2014 yes, they worship.", "translator_notes": ["The idol-making process is economic: gold purchased, silver weighed, craftsman hired. The god is a commercial product. The worshipper prostrates before what his money bought."], "reading_level": "9th grade"},
    {"verse": 7, "text_hebrew": "\u05d9\u05b4\u05e9\u05c2\u05bc\u05b8\u05d0\u05bb\u05d4\u05d5\u05bc \u05e2\u05b7\u05dc\u05be\u05db\u05bc\u05b8\u05ea\u05b5\u05e3 \u05d9\u05b4\u05e1\u05b0\u05d1\u05bc\u05b0\u05dc\u05bb\u05d4\u05d5\u05bc", "text_kjv": "They bear him upon the shoulder, they carry him, and set him in his place, and he standeth; from his place shall he not remove: yea, one shall cry unto him, yet can he not answer, nor save him out of his trouble.", "rendering": "They lift it to their shoulders, they carry it;\nthey set it in its place, and there it stands.\nFrom its spot it does not move.\nIf someone cries out to it, it does not answer;\nit cannot save anyone from distress.", "translator_notes": ["Five stages of total passivity: carried, set down, stands, cannot move, cannot respond. The final verdict: lo yoshiennu ('it cannot save') \u2014 the one function a god must perform, it cannot."], "reading_level": "9th grade"},
    {"verse": 8, "text_hebrew": "\u05d6\u05b4\u05db\u05b0\u05e8\u05d5\u05bc\u05be\u05d6\u05b9\u05d0\u05ea \u05d5\u05b0\u05d4\u05b4\u05ea\u05b0\u05d0\u05b9\u05e9\u05c1\u05b8\u05e9\u05c1\u05d5\u05bc", "text_kjv": "Remember this, and shew yourselves men: bring it again to mind, O ye transgressors.", "rendering": "Remember this and stand firm;\ntake it to heart, you rebels.", "translator_notes": ["The imperative calls the exiles to moral courage. The word posh'im ('rebels') addresses Israelites tempted by Babylonian religion."], "reading_level": "9th grade"},
    {"verse": 9, "text_hebrew": "\u05d6\u05b4\u05db\u05b0\u05e8\u05d5\u05bc \u05e8\u05b4\u05d0\u05e9\u05c1\u05b9\u05e0\u05d5\u05b9\u05ea \u05de\u05b5\u05e2\u05d5\u05b9\u05dc\u05b8\u05dd", "text_kjv": "Remember the former things of old: for I am God, and there is none else; I am God, and there is none like me,", "rendering": "Remember the former things of old,\nfor I am God, and there is no other;\nI am God, and there is none like me,", "translator_notes": ["The doubled self-identification with two negations ('no other,' 'none like me') is the chapter's theological climax. Memory is the antidote to idolatry."], "reading_level": "9th grade"},
    {"verse": 10, "text_hebrew": "\u05de\u05b7\u05d2\u05bc\u05b4\u05d9\u05d3 \u05de\u05b5\u05e8\u05b5\u05d0\u05e9\u05c1\u05b4\u05d9\u05ea \u05d0\u05b7\u05d7\u05b2\u05e8\u05b4\u05d9\u05ea", "text_kjv": "Declaring the end from the beginning, and from ancient times the things that are not yet done, saying, My counsel shall stand, and I will do all my pleasure:", "rendering": "declaring the end from the beginning,\nand from ancient times what is not yet done,\nsaying, 'My purpose will stand,\nand I will accomplish all my desire.'", "translator_notes": ["God's ability to declare the end from the beginning (maggid mereshit acharit) is the definitive proof of divinity no idol can match."], "reading_level": "9th grade"},
    {"verse": 11, "text_hebrew": "\u05e7\u05b9\u05e8\u05b5\u05d0 \u05de\u05b4\u05de\u05bc\u05b4\u05d6\u05b0\u05e8\u05b8\u05d7 \u05e2\u05b7\u05d9\u05b4\u05d8", "text_kjv": "Calling a ravenous bird from the east, the man that executeth my counsel from a far country: yea, I have spoken it, I will also bring it to pass; I have purposed it, I will also do it.", "rendering": "calling a bird of prey from the east,\nfrom a distant land the man of my purpose.\nI have spoken, and I will bring it about;\nI have planned, and I will do it.", "translator_notes": ["The 'bird of prey from the east' is Cyrus \u2014 swift, unstoppable, summoned from Persia. The phrase ish atsati ('man of my purpose') makes Cyrus God's instrument."], "reading_level": "9th grade"},
    {"verse": 12, "text_hebrew": "\u05e9\u05c1\u05b4\u05de\u05b0\u05e2\u05d5\u05bc \u05d0\u05b5\u05dc\u05b7\u05d9 \u05d0\u05b7\u05d1\u05bc\u05b4\u05d9\u05e8\u05b5\u05d9 \u05dc\u05b5\u05d1", "text_kjv": "Hearken unto me, ye stouthearted, that are far from righteousness:", "rendering": "Listen to me, you stubborn of heart,\nyou who are far from righteousness:", "translator_notes": ["The abbirei lev ('stubborn of heart') are Israelites who resist God's plan. Being 'far from righteousness' is the opposite of seeking God."], "reading_level": "9th grade"},
    {"verse": 13, "text_hebrew": "\u05e7\u05b5\u05e8\u05b7\u05d1\u05b0\u05ea\u05bc\u05b4\u05d9 \u05e6\u05b4\u05d3\u05b0\u05e7\u05b8\u05ea\u05b4\u05d9", "text_kjv": "I bring near my righteousness; it shall not be far off, and my salvation shall not tarry: and I will place salvation in Zion for Israel my glory.", "rendering": "I am bringing near my righteousness \u2014 it is not far off,\nand my salvation will not delay.\nI will place salvation in Zion,\nmy splendor upon Israel.", "translator_notes": ["God moves toward those who are 'far from righteousness' (v. 12) \u2014 He brings His righteousness near. The word tif'arti ('my splendor') applied to Israel means Israel will display God's glory. Salvation is placed 'in Zion' \u2014 specific, not abstract."], "reading_level": "9th grade"}
])

# ISAIAH 47
w(47, {
    "summary": "A taunt-song against Babylon, personified as Virgin Daughter Babylon. She descends from her throne to sit in the dust, exposed and humiliated. Her sorceries and enchantments cannot protect her. Her self-deifying claim 'I am, and there is no one besides me' is exposed as blasphemous.",
    "remarkable": "Babylon's declaration 'I am, and there is no one besides me' (vv. 8, 10) mirrors God's own exclusive claims (45:5-6, 46:9). The parody is deliberate: Babylon has made herself into a god. Her punishment fits her crime \u2014 absolute sovereignty meets absolute loss. The astrologers, star-gazers, and monthly prognosticators (v. 13) represent Babylon's famed divinatory tradition, now exposed as worthless. The chapter ends with total abandonment: 'there is no one to save you' (v. 15).",
    "friction": "The phrase betulat bat-Bavel ('Virgin Daughter Babylon') personifies the city as a young woman who has never been conquered. The 'virgin' implies invincibility now shattered. The sorcery vocabulary includes technical terms for Babylonian divination practices. We rendered each descriptively and noted the Babylonian context.",
    "connections": "The taunt echoes the king-of-Babylon song in 14:4-23. Babylon's fall is announced in 21:9 and culminates in Revelation 17-18. The 'I am' claim inverts Exodus 3:14. The sudden 'both in one day' judgment (v. 9) anticipates Revelation 18:8."
}, [
    {"verse": 1, "text_hebrew": "\u05e8\u05b0\u05d3\u05b4\u05d9 \u05d5\u05bc\u05e9\u05c1\u05b0\u05d1\u05b4\u05d9 \u05e2\u05b7\u05dc\u05be\u05e2\u05b8\u05e4\u05b8\u05e8", "text_kjv": "Come down, and sit in the dust, O virgin daughter of Babylon, sit on the ground: there is no throne, O daughter of the Chaldeans: for thou shalt no more be called tender and delicate.", "rendering": "Come down and sit in the dust,\nVirgin Daughter Babylon!\nSit on the ground without a throne,\nDaughter of the Chaldeans!\nFor you will no longer be called\ntender and delicate.", "translator_notes": ["The descent: from throne to dust, from palace to ground. The title betulat bat-Bavel personifies the city as a young woman who has never been conquered \u2014 now shattered."], "reading_level": "9th grade"},
    {"verse": 2, "text_hebrew": "\u05e7\u05b0\u05d7\u05b4\u05d9 \u05e8\u05b5\u05d7\u05b7\u05d9\u05b4\u05dd \u05d5\u05b0\u05d8\u05b7\u05d7\u05b2\u05e0\u05b4\u05d9 \u05e7\u05b8\u05de\u05b7\u05d7", "text_kjv": "Take the millstones, and grind meal: uncover thy locks, make bare the leg, uncover the thigh, pass over the rivers.", "rendering": "Take the millstones and grind flour.\nRemove your veil, strip off your skirt,\nbare your legs, wade through rivers.", "translator_notes": ["The queen becomes a slave: grinding at the mill was the lowest domestic labor. The progressive undressing describes the degradation of captivity."], "reading_level": "9th grade"},
    {"verse": 3, "text_hebrew": "\u05ea\u05bc\u05b4\u05d2\u05bc\u05b8\u05dc \u05e2\u05b6\u05e8\u05b0\u05d5\u05b8\u05ea\u05b5\u05da\u05b0", "text_kjv": "Thy nakedness shall be uncovered, yea, thy shame shall be seen: I will take vengeance, and I will not meet thee as a man.", "rendering": "Your nakedness will be exposed,\nyour shame will be seen.\nI will take vengeance,\nand I will spare no one.", "translator_notes": ["The exposure of nakedness is the ultimate humiliation in the ancient Near East. God is the agent: 'I will take vengeance.'"], "reading_level": "9th grade"},
    {"verse": 4, "text_hebrew": "\u05d2\u05bc\u05b9\u05d0\u05b2\u05dc\u05b5\u05e0\u05d5\u05bc \u05d9\u05b0\u05d4\u05d5\u05b8\u05d4 \u05e6\u05b0\u05d1\u05b8\u05d0\u05d5\u05b9\u05ea \u05e9\u05c1\u05b0\u05de\u05d5\u05b9", "text_kjv": "As for our redeemer, the LORD of hosts is his name, the Holy One of Israel.", "rendering": "Our Redeemer \u2014 the LORD of Hosts is His name \u2014\nthe Holy One of Israel.", "expanded_rendering": "The Hebrew go'alenu ('our Redeemer') interrupts the taunt with a confession: the one judging Babylon is Israel's kinsman-Redeemer. Three titles converge: go'alenu, YHWH tseva'ot, Qedosh Yisra'el \u2014 the God who redeems, commands armies, and is utterly set apart.", "translator_notes": ["A parenthetical doxology breaking into the taunt. The three titles identify the God who judges Babylon as the same God who redeems Israel."], "key_terms": [{"hebrew": "\u05d2\u05bc\u05b9\u05d0\u05b5\u05dc", "transliteration": "go'el", "rendered_as": "Redeemer", "semantic_range": "redeemer, kinsman-redeemer, one who reclaims what was lost", "note": "Capitalized when applied to God. The go'el acts on behalf of family \u2014 God's judgment of Babylon is a family rescue operation."}], "reading_level": "9th grade"},
    {"verse": 5, "text_hebrew": "\u05e9\u05c1\u05b0\u05d1\u05b4\u05d9 \u05d3\u05d5\u05bc\u05de\u05b8\u05dd \u05d5\u05bc\u05d1\u05b9\u05d0\u05b4\u05d9 \u05d1\u05b7\u05d7\u05b9\u05e9\u05c1\u05b6\u05da\u05b0", "text_kjv": "Sit thou silent, and get thee into darkness, O daughter of the Chaldeans: for thou shalt no more be called, The lady of kingdoms.", "rendering": "Sit in silence and go into darkness,\nDaughter of the Chaldeans,\nfor you will no longer be called\nmistress of kingdoms.", "translator_notes": ["Silence and darkness reverse Babylon's splendor. The title geveret mamlakhot ('mistress of kingdoms') is revoked."], "reading_level": "9th grade"},
    {"verse": 6, "text_hebrew": "\u05e7\u05b8\u05e6\u05b7\u05e4\u05b0\u05ea\u05bc\u05b4\u05d9 \u05e2\u05b7\u05dc\u05be\u05e2\u05b7\u05de\u05bc\u05b4\u05d9", "text_kjv": "I was wroth with my people, I have polluted mine inheritance, and given them into thine hand: thou didst shew them no mercy; upon the ancient hast thou very heavily laid thy yoke.", "rendering": "I was angry with my people;\nI profaned my inheritance\nand gave them into your hand.\nYou showed them no mercy;\non the elderly you made your yoke very heavy.", "translator_notes": ["God acknowledges His role in Israel's exile but charges Babylon with exceeding the mandate \u2014 showing no mercy and oppressing the elderly. The agent of judgment became an agent of cruelty."], "reading_level": "9th grade"},
    {"verse": 7, "text_hebrew": "\u05d5\u05b7\u05ea\u05bc\u05b9\u05d0\u05de\u05b0\u05e8\u05b4\u05d9 \u05dc\u05b0\u05e2\u05d5\u05b9\u05dc\u05b8\u05dd", "text_kjv": "And thou saidst, I shall be a lady for ever: so that thou didst not lay these things to thy heart, neither didst remember the latter end of it.", "rendering": "You said, 'I will be mistress forever' \u2014\nyou did not take these things to heart\nor consider how it would end.", "translator_notes": ["Babylon's fatal assumption: permanence. The failure to 'remember the end' is the opposite of God who declares 'the end from the beginning' (46:10)."], "reading_level": "9th grade"},
    {"verse": 8, "text_hebrew": "\u05d5\u05b0\u05e2\u05b7\u05ea\u05bc\u05b8\u05d4 \u05e9\u05c1\u05b4\u05de\u05b0\u05e2\u05b4\u05d9\u05be\u05d6\u05b9\u05d0\u05ea \u05e2\u05b2\u05d3\u05b4\u05d9\u05e0\u05b8\u05d4", "text_kjv": "Therefore hear now this, thou that art given to pleasures, that dwellest carelessly, that sayest in thine heart, I am, and none else beside me; I shall not sit as a widow, neither shall I know the loss of children:", "rendering": "Now hear this, you lover of pleasure,\nwho sits securely,\nwho says in her heart,\n'I am, and there is no one besides me.\nI will never sit as a widow\nor know the loss of children.'", "expanded_rendering": "The Hebrew ani ve'afsi od ('I am, and there is no one besides me') is Babylon's self-deification \u2014 she uses the exact formula God uses for His exclusive sovereignty (45:5-6, 46:9). The blasphemy is structural: a city speaks as though she were God.", "translator_notes": ["The phrase ani ve'afsi od deliberately echoes God's exclusive self-declarations. Babylon has committed the ultimate sin: claiming for herself what belongs to God alone."], "reading_level": "10th grade"},
    {"verse": 9, "text_hebrew": "\u05d5\u05b0\u05ea\u05b8\u05d1\u05b9\u05d0\u05e0\u05b8\u05d4 \u05dc\u05b8\u05da\u05b0 \u05e9\u05c1\u05b0\u05ea\u05bc\u05b5\u05d9\u05be\u05d0\u05b5\u05dc\u05bc\u05b6\u05d4", "text_kjv": "But these two things shall come to thee in a moment in one day, the loss of children, and widowhood: they shall come upon thee in their perfection for the multitude of thy sorceries, and for the great abundance of thine enchantments.", "rendering": "Both of these will come upon you\nin a moment, in a single day:\nbereavement and widowhood.\nThey will come upon you in full measure,\ndespite your many sorceries\nand the great power of your spells.", "translator_notes": ["What Babylon declared impossible (v. 8) happens in a single day. The sorceries and spells that Babylon trusted cannot prevent it."], "reading_level": "9th grade"},
    {"verse": 10, "text_hebrew": "\u05d5\u05b7\u05ea\u05bc\u05b4\u05d1\u05b0\u05d8\u05b0\u05d7\u05b4\u05d9 \u05d1\u05b0\u05e8\u05b8\u05e2\u05b8\u05ea\u05b5\u05da\u05b0", "text_kjv": "For thou hast trusted in thy wickedness: thou hast said, None seeth me. Thy wisdom and thy knowledge, it hath perverted thee; and thou hast said in thine heart, I am, and none else beside me.", "rendering": "You trusted in your wickedness;\nyou said, 'No one sees me.'\nYour wisdom and your knowledge\nled you astray,\nand you said in your heart,\n'I am, and there is no one besides me.'", "translator_notes": ["The self-deification formula appears again. Babylon's wisdom and knowledge became instruments of self-delusion. The assumption 'no one sees me' denies divine observation."], "reading_level": "9th grade"},
    {"verse": 11, "text_hebrew": "\u05d5\u05bc\u05d1\u05b8\u05d0 \u05e2\u05b8\u05dc\u05b7\u05d9\u05b4\u05da\u05b0 \u05e8\u05b8\u05e2\u05b8\u05d4", "text_kjv": "Therefore shall evil come upon thee; thou shalt not know from whence it riseth: and mischief shall fall upon thee; thou shalt not be able to put it off: and desolation shall come upon thee suddenly, which thou shalt not know.", "rendering": "But disaster will come upon you,\nand you will not know how to charm it away.\nCalamity will fall on you,\nand you will not be able to atone for it.\nDevastation will come upon you suddenly,\nbefore you know it.", "translator_notes": ["Three disasters with three inabilities: disaster that cannot be charmed, calamity that cannot be atoned for, devastation that cannot be anticipated. Babylon's entire repertoire fails."], "reading_level": "9th grade"},
    {"verse": 12, "text_hebrew": "\u05e2\u05b4\u05de\u05b0\u05d3\u05b4\u05d9\u05be\u05e0\u05b8\u05d0 \u05d1\u05b7\u05d7\u05b2\u05d1\u05b8\u05e8\u05b7\u05d9\u05b4\u05da\u05b0", "text_kjv": "Stand now with thine enchantments, and with the multitude of thy sorceries, wherein thou hast laboured from thy youth; if so be thou shalt be able to profit, if so be thou mayest prevail.", "rendering": "Stand now with your spells\nand your many sorceries,\nat which you have labored from your youth.\nPerhaps you can succeed;\nperhaps you can inspire terror.", "translator_notes": ["The sarcastic 'perhaps' mocks Babylon's expertise \u2014 after a lifetime of sorcery, maybe it will finally work."], "reading_level": "9th grade"},
    {"verse": 13, "text_hebrew": "\u05e0\u05b4\u05dc\u05b0\u05d0\u05b5\u05d9\u05ea \u05d1\u05bc\u05b0\u05e8\u05b9\u05d1 \u05e2\u05b2\u05e6\u05b8\u05ea\u05b8\u05d9\u05b4\u05da\u05b0", "text_kjv": "Thou art wearied in the multitude of thy counsels. Let now the astrologers, the stargazers, the monthly prognosticators, stand up, and save thee from these things that shall come upon thee.", "rendering": "You are wearied by your many counselors.\nLet them stand up now and save you \u2014\nthose who divide the heavens,\nwho gaze at the stars,\nwho at each new moon predict\nwhat will come upon you.", "translator_notes": ["Three categories of Babylonian divination: hovrei shamayim ('dividers of the heavens'), chozim bakkokhavim ('star-gazers'), modi'im lechodashim ('monthly prognosticators'). Babylonian astronomical records were the most sophisticated in the ancient world \u2014 and they are mocked as useless."], "reading_level": "9th grade"},
    {"verse": 14, "text_hebrew": "\u05d4\u05b4\u05e0\u05bc\u05b5\u05d4 \u05d4\u05b8\u05d9\u05d5\u05bc \u05db\u05bc\u05b0\u05e7\u05b7\u05e9\u05c1", "text_kjv": "Behold, they shall be as stubble; the fire shall burn them; they shall not deliver themselves from the power of the flame: there shall not be a coal to warm at, nor fire to sit before it.", "rendering": "Look \u2014 they are like stubble;\nfire burns them up.\nThey cannot save themselves\nfrom the power of the flame.\nThis is no coal for warming,\nno fire to sit before.", "translator_notes": ["The astrologers become fuel. The fire that destroys them is not even useful as a hearth \u2014 their destruction produces nothing of value."], "reading_level": "9th grade"},
    {"verse": 15, "text_hebrew": "\u05db\u05bc\u05b5\u05df \u05d4\u05b8\u05d9\u05d5\u05bc\u05be\u05dc\u05b8\u05da\u05b0", "text_kjv": "Thus shall they be unto thee with whom thou hast laboured, even thy merchants, from thy youth: they shall wander every one to his quarter; none shall save thee.", "rendering": "Such are those you have labored with \u2014\nyour traders from your youth.\nEach wanders off in his own direction;\nthere is no one to save you.", "translator_notes": ["Total abandonment. Babylon's commercial partners scatter. The final word moshi'ekh ('your savior') uses the salvation root \u2014 Babylon has none."], "reading_level": "9th grade"}
])

# ISAIAH 48
w(48, {
    "summary": "God rebukes Israel for stubbornness \u2014 He declared things long ago so they could not credit idols. He refines Israel in the furnace of affliction. For His own name's sake He delays anger. Cyrus is His instrument. 'Go out from Babylon!' The section closes: 'There is no peace for the wicked.'",
    "remarkable": "The chapter is God's most frustrated address to Israel in Second Isaiah. The command to leave Babylon (v. 20) is the climactic imperative of chapters 40-48. The closing refrain 'there is no peace for the wicked' (v. 22) divides Second Isaiah into three sections (48:22, 57:21, and implicitly 66:24).",
    "friction": "The phrase becharttikha velo bekhesef (v. 10) is textually difficult: 'I chose you' or 'I tested you'? We followed the Masoretic text. The kur oni ('furnace of affliction') describes exile as purposeful refining. The 'no peace' refrain is abrupt after the joy of v. 20 \u2014 the juxtaposition is intentional.",
    "connections": "The 'go out from Babylon' (v. 20) echoes Genesis 12:1 and anticipates Revelation 18:4. The refining-furnace image connects to Deuteronomy 4:20 and 1 Kings 8:51. The 'no peace' refrain recurs at 57:21."
}, [
    {"verse": 1, "text_hebrew": "\u05e9\u05c1\u05b4\u05de\u05b0\u05e2\u05d5\u05bc\u05be\u05d6\u05b9\u05d0\u05ea \u05d1\u05bc\u05b5\u05d9\u05ea\u05be\u05d9\u05b7\u05e2\u05b2\u05e7\u05b9\u05d1", "text_kjv": "Hear ye this, O house of Jacob, which are called by the name of Israel, and are come forth out of the waters of Judah, which swear by the name of the LORD, and make mention of the God of Israel, but not in truth, nor in righteousness.", "rendering": "Hear this, house of Jacob,\nyou who are called by the name of Israel\nand who came from the waters of Judah \u2014\nwho swear by the name of the LORD\nand invoke the God of Israel,\nbut not in truth or in righteousness.", "translator_notes": ["The opening is accusatory: Israel bears the right name and speaks the right words but lacks truth (emet) and righteousness (tsedaqah)."], "reading_level": "9th grade"},
    {"verse": 2, "text_hebrew": "\u05db\u05bc\u05b4\u05d9 \u05de\u05b5\u05e2\u05b4\u05d9\u05e8 \u05d4\u05b7\u05e7\u05bc\u05b9\u05d3\u05b6\u05e9\u05c1", "text_kjv": "For they call themselves of the holy city, and stay themselves upon the God of Israel; The LORD of hosts is his name.", "rendering": "For they call themselves after the holy city\nand lean on the God of Israel \u2014\nthe LORD of Hosts is His name.", "translator_notes": ["Israel claims Jerusalem and God as support, but the claim is hollow given v. 1's indictment."], "reading_level": "9th grade"},
    {"verse": 3, "text_hebrew": "\u05d4\u05b8\u05e8\u05b4\u05d0\u05e9\u05c1\u05b9\u05e0\u05d5\u05b9\u05ea \u05de\u05b5\u05d0\u05b8\u05d6 \u05d4\u05b4\u05d2\u05bc\u05b7\u05d3\u05b0\u05ea\u05bc\u05b4\u05d9", "text_kjv": "I have declared the former things from the beginning; and they went forth out of my mouth, and I shewed them; I did them suddenly, and they came to pass.", "rendering": "The former things I declared long ago;\nthey went out from my mouth and I announced them.\nThen suddenly I acted, and they came to pass.", "translator_notes": ["God's pattern: declare in advance, then act suddenly. The purpose is explained in v. 5."], "reading_level": "9th grade"},
    {"verse": 4, "text_hebrew": "\u05de\u05b4\u05d3\u05bc\u05b7\u05e2\u05b0\u05ea\u05bc\u05b4\u05d9 \u05db\u05bc\u05b4\u05d9 \u05e7\u05b8\u05e9\u05c1\u05b6\u05d4 \u05d0\u05b8\u05ea\u05bc\u05b8\u05d4", "text_kjv": "Because I knew that thou art obstinate, and thy neck is an iron sinew, and thy brow brass;", "rendering": "Because I knew how stubborn you are \u2014\nyour neck is an iron sinew,\nyour forehead is bronze \u2014", "translator_notes": ["Three metaphors for stubbornness: hard, iron-sinewed, bronze-faced. The metallic imagery makes resistance seem structural."], "reading_level": "9th grade"},
    {"verse": 5, "text_hebrew": "\u05d5\u05b8\u05d0\u05b7\u05d2\u05bc\u05b4\u05d9\u05d3 \u05dc\u05b0\u05da\u05b8 \u05de\u05b5\u05d0\u05b8\u05d6", "text_kjv": "I have even from the beginning declared it to thee; before it came to pass I shewed it thee: lest thou shouldest say, Mine idol hath done them, and my graven image, and my molten image, hath commanded them.", "rendering": "therefore I declared it to you long ago;\nbefore it happened I announced it to you,\nlest you say, 'My idol did this,\nmy carved image and my cast image commanded it.'", "translator_notes": ["The reason for advance declaration: to prevent idolatry from claiming credit. God's foreknowledge is both proof of divinity and prevention of false worship."], "reading_level": "9th grade"},
    {"verse": 6, "text_hebrew": "\u05e9\u05c1\u05b8\u05de\u05b7\u05e2\u05b0\u05ea\u05bc\u05b8 \u05d7\u05b2\u05d6\u05b5\u05d4 \u05db\u05bb\u05dc\u05bc\u05b8\u05d4\u05bc", "text_kjv": "Thou hast heard, see all this; and will not ye declare it? I have shewed thee new things from this time, even hidden things, and thou didst not know them.", "rendering": "You have heard \u2014 now look at all this!\nWill you not acknowledge it?\nFrom now on I announce new things to you,\nhidden things you have not known.", "translator_notes": ["God shifts from 'former things' to 'new things' and 'hidden things' \u2014 fresh revelations. The challenge demands a response."], "reading_level": "9th grade"},
    {"verse": 7, "text_hebrew": "\u05e2\u05b7\u05ea\u05bc\u05b8\u05d4 \u05e0\u05b4\u05d1\u05b0\u05e8\u05b0\u05d0\u05d5\u05bc", "text_kjv": "They are created now, and not from the beginning; even before the day when thou heardest them not; lest thou shouldest say, Behold, I knew them.", "rendering": "They are created now, not long ago;\nbefore today you have not heard of them,\nlest you say, 'I already knew that.'", "translator_notes": ["The 'new things' are created (nivr'u) at the moment of announcement, preventing Israel from claiming prior knowledge."], "reading_level": "9th grade"},
    {"verse": 8, "text_hebrew": "\u05d2\u05bc\u05b7\u05dd \u05dc\u05b9\u05d0\u05be\u05e9\u05c1\u05b8\u05de\u05b7\u05e2\u05b0\u05ea\u05bc\u05b8", "text_kjv": "Yea, thou heardest not; yea, thou knewest not; yea, from that time that thine ear was not opened: for I knew that thou wouldest deal very treacherously, and wast called a transgressor from the womb.", "rendering": "You have neither heard nor known;\nfrom of old your ear has not been opened.\nFor I knew you would act utterly treacherously;\nyou have been called a rebel from the womb.", "translator_notes": ["The indictment intensifies: chronic deafness, innate treachery, a rebel from birth."], "reading_level": "9th grade"},
    {"verse": 9, "text_hebrew": "\u05dc\u05b0\u05de\u05b7\u05e2\u05b7\u05df \u05e9\u05c1\u05b0\u05de\u05b4\u05d9 \u05d0\u05b7\u05d0\u05b2\u05e8\u05b4\u05d9\u05da\u05b0 \u05d0\u05b7\u05e4\u05bc\u05b4\u05d9", "text_kjv": "For my name's sake will I defer mine anger, and for my praise will I refrain for thee, that I cut thee not off.", "rendering": "For the sake of my name I defer my anger;\nfor the sake of my praise I hold it back from you,\nso as not to cut you off.", "translator_notes": ["God's mercy is grounded in His own name, not Israel's merit. The verb a'arikh uses the same root as erekh appayim ('slow to anger,' Exodus 34:6)."], "reading_level": "9th grade"},
    {"verse": 10, "text_hebrew": "\u05d4\u05b4\u05e0\u05bc\u05b5\u05d4 \u05e6\u05b0\u05e8\u05b7\u05e4\u05b0\u05ea\u05bc\u05b4\u05d9\u05da\u05b8", "text_kjv": "Behold, I have refined thee, but not with silver; I have chosen thee in the furnace of affliction.", "rendering": "Look \u2014 I have refined you, but not as silver;\nI have tested you in the furnace of affliction.", "translator_notes": ["God's refining did not apply the full heat \u2014 Israel would not survive silver-standard purification. Exile is the furnace (kur oni), painful but purposeful."], "reading_level": "9th grade"},
    {"verse": 11, "text_hebrew": "\u05dc\u05b0\u05de\u05b7\u05e2\u05b2\u05e0\u05b4\u05d9 \u05dc\u05b0\u05de\u05b7\u05e2\u05b2\u05e0\u05b4\u05d9 \u05d0\u05b6\u05e2\u05b1\u05e9\u05c2\u05b6\u05d4", "text_kjv": "For mine own sake, even for mine own sake, will I do it: for how should my name be polluted? and I will not give my glory unto another.", "rendering": "For my own sake, for my own sake, I act \u2014\nfor how should my name be profaned?\nMy glory I will not give to another.", "translator_notes": ["The doubled lema'ani lema'ani is strikingly honest: God acts for His own reputation. The refusal to give kavod to another echoes 42:8."], "reading_level": "9th grade"},
    {"verse": 12, "text_hebrew": "\u05e9\u05c1\u05b0\u05de\u05b7\u05e2 \u05d0\u05b5\u05dc\u05b7\u05d9 \u05d9\u05b7\u05e2\u05b2\u05e7\u05b9\u05d1", "text_kjv": "Hearken unto me, O Jacob and Israel, my called; I am he; I am the first, I also am the last.", "rendering": "Listen to me, Jacob,\nand Israel, whom I called:\nI am He; I am the first,\nand I am the last.", "translator_notes": ["The triple self-identification \u2014 ani hu, ani rishon, ani acharon \u2014 compresses God's identity. The 'first and last' appears in 41:4, 44:6 and Revelation 1:17, 22:13."], "reading_level": "9th grade"},
    {"verse": 13, "text_hebrew": "\u05d0\u05b7\u05e3\u05be\u05d9\u05b8\u05d3\u05b4\u05d9 \u05d9\u05b8\u05e1\u05b0\u05d3\u05b8\u05d4 \u05d0\u05b6\u05e8\u05b6\u05e5", "text_kjv": "Mine hand also hath laid the foundation of the earth, and my right hand hath spanned the heavens: when I call unto them, they stand up together.", "rendering": "My hand laid the foundation of the earth,\nand my right hand spread out the heavens.\nWhen I call to them,\nthey stand together.", "translator_notes": ["God as architect: His hand laid earth, His right hand stretched heavens. Creation responds to His voice like servants at attention."], "reading_level": "9th grade"},
    {"verse": 14, "text_hebrew": "\u05d4\u05b4\u05e7\u05bc\u05b8\u05d1\u05b0\u05e6\u05d5\u05bc \u05db\u05bb\u05dc\u05bc\u05b0\u05db\u05b6\u05dd", "text_kjv": "All ye, assemble yourselves, and hear; which among them hath declared these things? The LORD hath loved him: he will do his pleasure on Babylon, and his arm shall be on the Chaldeans.", "rendering": "Assemble, all of you, and listen.\nWhich of them declared these things?\nThe LORD loves him \u2014\nhe will carry out His purpose against Babylon,\nand his arm will be against the Chaldeans.", "translator_notes": ["The 'him' is Cyrus, described as God's beloved instrument of judgment against Babylon."], "reading_level": "9th grade"},
    {"verse": 15, "text_hebrew": "\u05d0\u05b2\u05e0\u05b4\u05d9 \u05d0\u05b2\u05e0\u05b4\u05d9 \u05d3\u05bc\u05b4\u05d1\u05bc\u05b7\u05e8\u05b0\u05ea\u05bc\u05b4\u05d9", "text_kjv": "I, even I, have spoken; yea, I have called him: I have brought him, and he shall make his way prosperous.", "rendering": "I, even I, have spoken;\nindeed I have called him.\nI have brought him, and he will succeed.", "translator_notes": ["The emphatic ani ani ('I, even I') emphasizes that Cyrus's call and success are entirely God's doing."], "reading_level": "9th grade"},
    {"verse": 16, "text_hebrew": "\u05e7\u05b4\u05e8\u05b0\u05d1\u05d5\u05bc \u05d0\u05b5\u05dc\u05b7\u05d9 \u05e9\u05c1\u05b4\u05de\u05b0\u05e2\u05d5\u05bc \u05d6\u05b9\u05d0\u05ea", "text_kjv": "Come ye near unto me, hear ye this; I have not spoken in secret from the beginning; from the time that it was, there am I: and now the Lord GOD, and his Spirit, hath sent me.", "rendering": "Come near to me and hear this:\nFrom the beginning I have not spoken in secret;\nfrom the time it came to be, I was there.\nAnd now the Lord GOD has sent me,\nand His Spirit.", "translator_notes": ["The speaker shifts \u2014 'the Lord GOD has sent me and His Spirit' introduces a commissioned voice. The identity is debated: the Servant, the prophet, or a divine figure. We render as the Hebrew presents it."], "reading_level": "10th grade"},
    {"verse": 17, "text_hebrew": "\u05db\u05bc\u05b9\u05d4\u05be\u05d0\u05b8\u05de\u05b7\u05e8 \u05d9\u05b0\u05d4\u05d5\u05b8\u05d4 \u05d2\u05bc\u05b9\u05d0\u05b7\u05dc\u05b0\u05da\u05b8", "text_kjv": "Thus saith the LORD, thy Redeemer, the Holy One of Israel; I am the LORD thy God which teacheth thee to profit, which leadeth thee by the way that thou shouldest go.", "rendering": "This is what the LORD says \u2014\nyour Redeemer, the Holy One of Israel:\nI am the LORD your God,\nwho teaches you for your benefit,\nwho leads you in the way you should go.", "translator_notes": ["Three titles: YHWH, go'alekha ('your Redeemer'), Qedosh Yisra'el ('the Holy One of Israel'). Two present participles: melammedkha ('teaching you') and madrikhakha ('leading you')."], "key_terms": [{"hebrew": "\u05d2\u05bc\u05b9\u05d0\u05b5\u05dc", "transliteration": "go'el", "rendered_as": "Redeemer", "semantic_range": "redeemer, kinsman-redeemer, one who reclaims", "note": "Capitalized for God. Here paired with the Holy One of Israel."}], "reading_level": "9th grade"},
    {"verse": 18, "text_hebrew": "\u05dc\u05d5\u05bc \u05d4\u05b4\u05e7\u05b0\u05e9\u05c1\u05b7\u05d1\u05b0\u05ea\u05bc\u05b8 \u05dc\u05b0\u05de\u05b4\u05e6\u05b0\u05d5\u05b9\u05ea\u05b8\u05d9", "text_kjv": "O that thou hadst hearkened to my commandments! then had thy peace been as a river, and thy righteousness as the waves of the sea:", "rendering": "If only you had paid attention to my commands!\nThen your peace would have been like a river,\nand your righteousness like the waves of the sea.", "translator_notes": ["God grieves what might have been: shalom like a river (constant, flowing) and tsedaqah like sea waves (overwhelming). Disobedience cost them this."], "reading_level": "9th grade"},
    {"verse": 19, "text_hebrew": "\u05d5\u05b7\u05d9\u05b0\u05d4\u05b4\u05d9 \u05db\u05b7\u05d7\u05d5\u05b9\u05dc \u05d6\u05b7\u05e8\u05b0\u05e2\u05b6\u05da\u05b8", "text_kjv": "Thy seed also had been as the sand, and the offspring of thy bowels like the gravel thereof; his name should not have been cut off nor destroyed from before me.", "rendering": "Your offspring would have been like the sand,\nyour descendants like its grains.\nTheir name would never have been cut off\nor destroyed from before me.", "translator_notes": ["The Abrahamic promise (Genesis 22:17) would have been fully realized. The conditional mood carries unrealized potential."], "reading_level": "9th grade"},
    {"verse": 20, "text_hebrew": "\u05e6\u05b0\u05d0\u05d5\u05bc \u05de\u05b4\u05d1\u05bc\u05b8\u05d1\u05b6\u05dc \u05d1\u05bc\u05b4\u05e8\u05b0\u05d7\u05d5\u05bc \u05de\u05b4\u05db\u05bc\u05b7\u05e9\u05c2\u05b0\u05d3\u05bc\u05b4\u05d9\u05dd", "text_kjv": "Go ye forth of Babylon, flee ye from the Chaldeans, with a voice of singing declare ye, tell this, utter it even to the end of the earth; say ye, The LORD hath redeemed his servant Jacob.", "rendering": "Go out from Babylon!\nFlee from the Chaldeans!\nWith a shout of joy declare it,\nproclaim it, send it out\nto the ends of the earth.\nSay, 'The LORD has redeemed His servant Jacob!'", "expanded_rendering": "The imperative tse'u mibbavel ('go out from Babylon') is the climactic command of Second Isaiah's first section. The verb ga'al ('redeemed') declares the new exodus complete \u2014 God has acted as go'el, the kinsman who buys back what was lost.", "translator_notes": ["Six imperatives in rapid succession: go out, flee, declare, proclaim, send out, say. The final declaration ga'al YHWH avdo Ya'aqov uses the go'el verb \u2014 redemption accomplished."], "key_terms": [{"hebrew": "\u05d2\u05bc\u05b8\u05d0\u05b7\u05dc", "transliteration": "ga'al", "rendered_as": "redeemed", "semantic_range": "to redeem, to act as kinsman-redeemer, to buy back", "note": "The verb form of go'el. God has acted as Israel's nearest kin, purchasing freedom from Babylon."}], "reading_level": "9th grade"},
    {"verse": 21, "text_hebrew": "\u05d5\u05b0\u05dc\u05b9\u05d0 \u05e6\u05b8\u05de\u05b0\u05d0\u05d5\u05bc \u05d1\u05bc\u05b8\u05d7\u05b3\u05e8\u05b8\u05d1\u05d5\u05b9\u05ea \u05d4\u05d5\u05b9\u05dc\u05b4\u05d9\u05db\u05b8\u05dd", "text_kjv": "And they thirsted not when he led them through the deserts: he caused the waters to flow out of the rock for them: he clave the rock also, and the waters gushed out.", "rendering": "They did not thirst\nwhen He led them through the deserts.\nHe made water flow from the rock for them;\nHe split the rock, and water gushed out.", "translator_notes": ["Exodus imagery: God splitting rock and water gushing echoes Exodus 17:6 and Numbers 20:11. The new exodus mirrors the original."], "reading_level": "9th grade"},
    {"verse": 22, "text_hebrew": "\u05d0\u05b5\u05d9\u05df \u05e9\u05c1\u05b8\u05dc\u05d5\u05b9\u05dd \u05d0\u05b8\u05de\u05b7\u05e8 \u05d9\u05b0\u05d4\u05d5\u05b8\u05d4 \u05dc\u05b8\u05e8\u05b0\u05e9\u05c1\u05b8\u05e2\u05b4\u05d9\u05dd", "text_kjv": "There is no peace, saith the LORD, unto the wicked.", "rendering": "\"There is no peace,\" says the LORD,\n\"for the wicked.\"", "translator_notes": ["The section divider: Second Isaiah's first third (chs. 40-48) ends here. The same refrain at 57:21 ends the second third. The word shalom encompasses all wholeness \u2014 the wicked are excluded from it entirely."], "key_terms": [{"hebrew": "\u05e9\u05c1\u05b8\u05dc\u05d5\u05b9\u05dd", "transliteration": "shalom", "rendered_as": "peace", "semantic_range": "peace, wholeness, well-being, completeness, flourishing", "note": "The denial of shalom is the most absolute exclusion possible. This refrain structures Second Isaiah into three parts."}], "reading_level": "9th grade"}
])

print("\nIsaiah 46-48 complete")
